### ISSUE TITLE
Can't load document symbols and CTRL click classes

### ISSUE THREAD

**Issue by eLBati** [odoo-ide/vscode-odoo#36]
Hello,
see the following video about the right sidebar and ctrlclicking on `AbstractModel`: it seems to load forever.
Is this a known behavior?
Thanks!

![vs](https://github.com/odoo-ide/vscode-odoo/assets/1033131/983a68cf-2aad-4888-a729-344a2afaa6e3)

**Comment by trinhanhngoc** [comment]
Hello @eLBati ,

What version of the Odoo extension are you using? I just tested again but didn't see any problems.

https://github.com/odoo-ide/vscode-odoo/assets/11208291/a557807d-134c-4f88-99fd-3aa6921ed8aa

**Comment by eLBati** [comment]
Hello @trinhanhngoc ,

I am using v0.10.1

Also, I am using VS code over SSH on a remote folder and when installing "Odoo IDE" extension I get the message

> The pylance language server for Python will be automatically disabled for this workspace. This workspace will use the Odoo language server instead.

**Comment by trinhanhngoc** [comment]
@eLBati ,

There are no problems with the message. However, I also could not reproduce the problem even with remote development using SSH.

**Comment by eLBati** [comment]
@trinhanhngoc could you suggest me a way to analyze/debug further?

**Comment by trinhanhngoc** [comment]
@eLBati ,

You can try temporarily disabling the Odoo IDE plugin and switching the Python language server setting (in Workspace Settings) to Default , then check again to tell me if the problem still exists.

<img width="1097" alt="image" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/f57de003-299f-4ef8-a359-0e2eed73981a">

**Comment by eLBati** [comment]
> You can try temporarily disabling the Odoo IDE plugin and switching the Python language server setting (in Workspace Settings) to Default , then check again to tell me if the problem still exists.

Hello @trinhanhngoc , disabling Odoo IDE plugin and setting language server to default, the outline is working

**Comment by trinhanhngoc** [comment]
@eLBati ,

You can try disabling both the Odoo IDE extension and the Pylance extension, then install the Pyright extension and check again. Since the Odoo IDE extension is based on the Pyright extension, I want to confirm if the root problem is with Pyright.

**Comment by trinhanhngoc** [comment]
@eLBati 

Does the problem happen right after opening VSCode or after using it for a while?

**Comment by eLBati** [comment]
Hello @trinhanhngoc 

I removed Pylance and installed Pyright: outline was working fine.

Than I installed Odoo IDE: Pylance is automatically installed and outline and ctrlclick is not working anymore.

If I try to uninstall Pylance again, I get
> Please disable the Pyright extension for this workspace. This workspace will use the Odoo extension instead.

and

> Cannot uninstall 'Python' extension. 'Odoo IDE' extension depends on this.


Do you need more info from the logs?
Where can I find them?

Thanks!

**Comment by eLBati** [comment]
> Does the problem happen right after opening VSCode or after using it for a while?

The problem occurs right after opening

**Comment by trinhanhngoc** [comment]
@eLBati , 

What happens if you have only one python file (e.g. `mail_thread.py`) opened right after opening VSCode? Does the problem still exist?

**Comment by eLBati** [comment]
@trinhanhngoc this is what's happening opening VScode:

![vs](https://github.com/odoo-ide/vscode-odoo/assets/1033131/4b56a050-a997-47bc-bf9d-1c59afc5852d)

**Comment by trinhanhngoc** [comment]
@eLBati ,

I need some logs to debug. You can add these lines to your settings to make the logs more useful:

```
"odoo-ide.trace.server": "verbose",
"python.analysis.logLevel": "Trace"
```

Then, you disable Pyright and restart VSCode. When the problem occurs, you open the output panel and copy the logs for me.
<img width="1068" alt="Screenshot 2023-10-24 at 15 52 30" src="https://github.com/odoo-ide/vscode-odoo/assets/11208291/4f3edab0-5e04-4cc5-956c-8af532512bb2">

**Comment by eLBati** [comment]
Hello @trinhanhngoc 
here is the output
[temp2.txt](https://github.com/odoo-ide/vscode-odoo/files/13120233/temp2.txt)

**Comment by eLBati** [comment]
@trinhanhngoc I also tried this: removed every python extension and configuration about `python.languageServer`, installed Pyright, installed Odoo IDE.
Got the error messages:
`command 'pyright.createtypestub' already exists`
and
```
2023-10-25 06:37:36.832 [info] (Client) Another instance of Pylance or Pyright has been detected. Waiting up to 10 seconds for it to cease operation.
2023-10-25 06:37:47.352 [info] (Client) The existing extension didn't exit within 10 seconds. New instance will start, but you might encounter issues.
2023-10-25 06:37:47.800 [info] [Info  - 06:37:47] (2939589) Pylance language server 2023.10.40 (pyright 088ebaa5) starting
2023-10-25 06:37:47.800 [info] [Info  - 06:37:47] (2939589) Server root directory: /home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist
2023-10-25 06:37:47.825 [info] [Info  - 06:37:47] (2939589) Starting service instance "odoo14"
2023-10-25 06:37:47.852 [info] [Error - 06:37:47] Server initialization failed.
2023-10-25 06:37:47.852 [info] Error: command 'pyright.createtypestub' already exists
	at n.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:126:82889)
	at Object.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:141:20485)
	at t.ExecuteCommandFeature.register (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142847)
	at t.ExecuteCommandFeature.initialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142426)
	at E.initializeFeatures (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2092947)
	at E.doInitialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2079761)
	at async E.start (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2076776)
	at async Object.start (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166562)
	at async _0x374d7c.<computed>._startClient (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110383)
	at async _0x374d7c.<computed>._createNewRequest (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109848)
2023-10-25 06:37:47.852 [info] [Error - 06:37:47] Pylance client: couldn't create connection to server.
2023-10-25 06:37:47.852 [info] Error: command 'pyright.createtypestub' already exists
	at n.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:126:82889)
	at Object.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:141:20485)
	at t.ExecuteCommandFeature.register (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142847)
	at t.ExecuteCommandFeature.initialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142426)
	at E.initializeFeatures (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2092947)
	at E.doInitialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2079761)
	at async E.start (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2076776)
	at async Object.start (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166562)
	at async _0x374d7c.<computed>._startClient (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110383)
	at async _0x374d7c.<computed>._createNewRequest (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109848)
2023-10-25 06:37:47.852 [info] [Error - 06:37:47] Sending document notification textDocument/didOpen failed
2023-10-25 06:37:47.852 [info] Error: command 'pyright.createtypestub' already exists
	at n.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:126:82889)
	at Object.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:141:20485)
	at t.ExecuteCommandFeature.register (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142847)
	at t.ExecuteCommandFeature.initialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142426)
	at E.initializeFeatures (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2092947)
	at E.doInitialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2079761)
	at async E.start (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2076776)
	at async Object.start (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166562)
	at async _0x374d7c.<computed>._startClient (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110383)
	at async _0x374d7c.<computed>._createNewRequest (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109848)
2023-10-25 06:37:47.852 [info] [Error - 06:37:47] Sending document notification textDocument/didOpen failed
2023-10-25 06:37:47.852 [info] Error: command 'pyright.createtypestub' already exists
	at n.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:126:82889)
	at Object.registerCommand (/home/utente/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:141:20485)
	at t.ExecuteCommandFeature.register (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142847)
	at t.ExecuteCommandFeature.initialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2142426)
	at E.initializeFeatures (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2092947)
	at E.doInitialize (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2079761)
	at async E.start (/home/utente/.vscode-server/extensions/ms-python.python-2023.18.0/out/client/extension.js:2:2076776)
	at async Object.start (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:166562)
	at async _0x374d7c.<computed>._startClient (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:110383)
	at async _0x374d7c.<computed>._createNewRequest (/home/utente/.vscode-server/extensions/ms-python.vscode-pylance-2023.10.40/dist/extension.bundle.js:1:109848)
```

**Comment by eLBati** [comment]
> Since the Odoo IDE extension is based on the Pyright extension

I don't understand this: if Odoo IDE is based on Pyright, why Pylance is automatically installed when installing Odoo IDE?

Thanks

**Comment by trinhanhngoc** [comment]
Hello @eLBati ,

Thank you for the logs, I will debug it soon. I will explain more details about relationships between Odoo IDE, Pyright and Pylance:

1. Pyright: Microsoft's open-source Python type checker. It also has a basic Python language server (provide code completion, navigation, diagnostics,...) that is included in the Pyright extension.
2. Pylance: Microsoft's property Python language server. Pylance is built on top of Pyright. The Pylance extension is automatically installed when installing the Python extension.
3. Odoo IDE: like Pylance, it's also built on top of Pyright but with support for Odoo frameworks. The Odoo IDE extension depends on the Python extension, so when you install the Odoo IDE extension, the Python (and Pylance) extension will be installed. You can disable (or uninstall) the Pylance extension later.

The Python extension has a setting to select which Python language server to use. The default language server is Pylance. Other options are Jedi and None (disable Pylance and Jedi). When you install the Odoo IDE extension, the Odoo IDE extension will automatically update the Python language server setting to None for Odoo-related workspaces.

When using the Odoo IDE extension, you should disable or uninstall the Pyright extension. For the Pylance extension, the Odoo IDE extension will automatically disable it through the Python language server setting.

**Comment by trinhanhngoc** [comment]
@eLBati ,

After reading your log file, I found a permission denied error:

```
Error: EACCES: permission denied, scandir '/home/utente/odoo/instances/odoo16/postgres-data/odoo'
    at Object.readdirSync (node:fs:1454:3)
    at Object.e.isPythonPackageFolder (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:231674)
    at Object.t [as isOdooPackageContainingFolder] (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:297670)
    at t.OdooPythonImportResolverExtension._findOdooPackageContainingFolder (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:290458)
    at t.OdooPythonImportResolverExtension.updateExtraPaths (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:290001)
    at Object.e.updateExtraPaths (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:224300)
    at a._updateConfigOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:223524)
    at a.setConfigOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:223369)
    at a.setConfigOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:710085)
    at t.BackgroundAnalysisProgram.setConfigOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:307505)
    at b.setOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:759183)
    at Function.runWithOptions (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:1454645)
    at I.updateOptionsAndRestartService (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:1433665)
    at I.updateSettingsForWorkspace (/home/utente/.vscode-server/extensions/trinhanhngoc.vscode-odoo-0.10.1-linux-x64/dist/server.js:53:1433446)
    at async Promise.all (index 0)
```

I am not sure if this error is the root cause of the problem, but I will fix it soon and wait for your feedback again.

**Comment by trinhanhngoc** [comment]
@eLBati ,

I just published the new version 0.11.1, and I believe that it will fix your problem. You can update the extension and give me feedback.

**Comment by eLBati** [comment]
@trinhanhngoc thanks a lot!

The situation seems much better now.

I still have problems with ctrlclicking odoo classes like `models.AbstractModel` from "extra modules":

![vs](https://github.com/odoo-ide/vscode-odoo/assets/1033131/2295d3fc-4ff9-49ed-94da-24d420ce7fa6)

**Comment by trinhanhngoc** [comment]
@eLBati ,

I am pretty sure the problem is related to your project structure. How is your project structured?

**Comment by eLBati** [comment]
Hello @trinhanhngoc 

I have odoo repo at the same level of OCA repo:

![vs](https://github.com/odoo-ide/vscode-odoo/assets/1033131/ac21d7b0-d87a-4aab-b0d6-29ea15f757ee)

I also tried adding `"python.analysis.extraPaths": ["/home/utente/odoo/instances/odoo14/parts/odoo/odoo"]` to workspace settings but no difference.

Thanks!

**Comment by trinhanhngoc** [comment]
@eLBati ,

If `/home/utente/odoo/instances/odoo14/parts/odoo` is the path to the Odoo source code (contains `odoo`, `addons`, `odoo-bin`,...) then `/home/utente/odoo/instances/odoo14/parts/odoo` should be added to the extra paths setting instead of `/home/utente/odoo/instances/odoo14/parts/odoo`<s>/odoo</s>.

**Comment by eLBati** [comment]
@trinhanhngoc Thanks a lot!
