### ISSUE TITLE
Modules not resolved

### ISSUE THREAD

**Issue by adsummertech** [odoo-ide/vscode-odoo#7]
Hello.

I've installed the extension and disabled the Python Language Server as per the readme, however the editor is still not resolving any of the modules.

![image](https://user-images.githubusercontent.com/127057765/222997949-b13a6b08-ca0b-4b56-9a4e-84f3658cc403.png)

**Comment by adsummertech** [comment]
Copying the `odoo` folder from the source to my python `Libs` directory seemed to help, however Pyright was still struggling to find various definitions.

Switching back to Pylance with the odoo source in the `Libs` folder seems to offer the best support.

**Comment by trinhanhngoc** [comment]
Hi @adsummertech , the Odoo extension supports resolving imports like `from odoo.addons.xxx` where addon `xxx` can come from different addons paths attached to your VSCode workspace. Other imports like `from odoo import` are resolved in the same way as by the default Python Language Server. Please make sure that you are structuring your Odoo workspace correctly in VSCode. You can use the following sample structure:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/11208291/223015067-987a50dd-a0e4-4fc2-b515-7a9acffeefb6.png">

We have a multi-root workspace with three folders (three projects):

- odoo16 (https://github.com/odoo/odoo)
- account-invoicing16 (https://github.com/OCA/account-invoicing)
- stock-logistics-warehouse16 (https://github.com/OCA/stock-logistics-warehouse)

We also need to setup project dependencies for this workspace by `pyrightconfig.json` (same for Pylance) (https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

- `account-invoicing16` depends on `odoo16`, so `account-invoicing16/pyrightconfig.json` will be like:
```json
{
    "exclude": [
        "setup"
    ],
    "extraPaths": [
        "../odoo16"
    ]
}
```

- `stock-logistics-warehouse16` depends on `odoo16`, so `stock-logistics-warehouse16/pyrightconfig.json` will be like:
```json
{
    "exclude": [
        "setup"
    ],
    "extraPaths": [
        "../odoo16"
    ]
}
```

**Comment by adsummertech** [comment]
Thanks for the info but I still get various errors using Pyright - it seems it doesn't want to resolve `Model` from `models` or `fields.Many2one` etc etc.

See:
![image](https://user-images.githubusercontent.com/127057765/223017040-0f22b112-acdf-42d7-a09e-d0779c3e5837.png)

![image](https://user-images.githubusercontent.com/127057765/223017067-b9b9dd13-e88b-4726-9802-f490c41cb6bb.png)

This doesn't happen if I switch back to Pylance for the default language server.

I'm also not really running locally and just opening modules as projects and deploying elsewhere, so I found it easier to copy odoo to the python libs dir, but will look into if theres a global extraPaths option.

**Comment by adsummertech** [comment]
I'm not running odoo locally, just working on modules and deploying elsewhere, so that set up doesn't really work for me. I found that copying odoo to the python Libs dir worked best, but will look at a global extraPaths value.

However I'm still getting completion and reference errors when using Pyright. Can't find `model.Model` and `fields.Many2many` etc etc etc

![image](https://user-images.githubusercontent.com/127057765/223020199-464195ce-7b00-4a52-8f1c-e336b79ceab7.png)

![image](https://user-images.githubusercontent.com/127057765/223020226-c221a001-bfe0-4a62-b45a-622f5d4c2ada.png)

This doesn't happen if I use Pylance as the language server

**Comment by trinhanhngoc** [comment]
As you know, there is no difference in import resolution mechanism between Pylance and Pyright. I see there is duplicated tooltip information in your screenshots. Did you also install the Pyright extension (https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright) beside Pylance?

**Comment by adsummertech** [comment]
I had Pylance disabled and Pyright enabled.
Language server was set to none.

**Comment by trinhanhngoc** [comment]
Can you provide details on how you are structuring your project so I can reproduce the problem on my machine?

**Comment by adsummertech** [comment]
It's just a directory of modules, each with a __init__ and __manifest__ - not an entire project.

I really just wanted code completion and not sure I need the features of this extension so I think I will stick to pylance with odoo in my lib dir.
