### ISSUE TITLE
Pyright false positive?

### ISSUE THREAD

**Issue by dannyadair** [odoo-ide/vscode-odoo#95]
Everything seems to be working fine (thank you!) except for this Pyright complaint:

![Image](https://github.com/user-attachments/assets/eb66934a-7a03-41be-9841-162bb04fbedf)

When I "Go to Definition" you can see SENTINEL is very much an attribute, but it was imported from tools.misc:

![Image](https://github.com/user-attachments/assets/d9c059e0-5b6e-4376-937c-f9644ecc229c)

A few lines down in fields.py the same issue BUT not for NewId:

![Image](https://github.com/user-attachments/assets/750599f0-9cec-4dba-974e-343370b288c2)

Even though all of them are defined on the top level of api.py:

![Image](https://github.com/user-attachments/assets/e3c88007-0bb4-44d7-8f0d-7fd776c1eb36)

Maybe also worth noting that none of them are in `__all__`:

![Image](https://github.com/user-attachments/assets/9e83eca1-4f99-4daf-a99c-4f1e09b3229f)

What am I doing wrong, what config am I missing?
Thank you for your help!

**Comment by dannyadair** [comment]
P.S.: Sorry I should add: I'm using the VSCode fork [Cursor](https://cursor.com), and while Pyright itself is disabled, there is a "Cursor Pyright":

![Image](https://github.com/user-attachments/assets/b56a14b5-0454-4f21-93b5-c41d4207cf1d)

However, I do have `"python.languageServer": "None"` in my .code-workspace file (I think Odoo IDE wrote that actually)

**Comment by trinhanhngoc** [comment]
Hello @dannyadair ,

I think the errors related to `SENTINEL`, `ContextType`,... are Odoo's issues. They should be fixed in the Odoo source code. Regarding Cursor Pyright, you should disable it manually. The `python.languageServer` setting is to disable two built-in language servers `Pylance` and `Jedi`, it cannot disable other language servers (Pyright, Cursor Pyright).

**Comment by dannyadair** [comment]
Thank you @trinhanhngoc 
I disabled Cursor Pyright but I'm still getting the same Pyright warning. So this is coming from the Pyright underneath Odoo IDE?

Installed modules:
- Better Jinja
- Command Variable
- Debugger for Firefox
- Docker
- Docker Compose
- ESLint
- favorites
- gettext
- Invoke (Python Task Executor)
- Odoo IDE
- Prettier
- Pylance
- Pylint
- Python
- Python Debugger
- Remote - SSH
- Remote Explorer
- reStructuredText
- Ruff
- Tasks
- XML
(- "Cursor Pyright" manually disabled)


This is what I have in Output for Odoo IDE:
```
[Info  - 14:46:59] Pyright language server 1.1.396 starting
[Info  - 14:46:59] Server root directory: file:///home/danny/.cursor/extensions/trinhanhngoc.vscode-odoo-0.38.4-linux-x64/dist
[Info  - 14:46:59] Data storage path: /home/danny/.config/Cursor/User/workspaceStorage/4e81fdc80da6eab5283bae68e6fa693f/trinhanhngoc.vscode-odoo
[Info  - 14:46:59] Starting service instance "odoo-18.0"
Received pythonPath from Python extension: /bin/python3.12
[Info  - 14:47:00] Background analysis(2) root directory: file:///home/danny/.cursor/extensions/trinhanhngoc.vscode-odoo-0.38.4-linux-x64/dist
[Info  - 14:47:00] Background analysis(2) started
[Info  - 14:47:00] Setting pythonPath for service "odoo-18.0": "/bin/python3.12"
[Info  - 14:47:00] No include entries specified; assuming /home/danny/src/odoo-18.0
[Info  - 14:47:00] Auto-excluding **/node_modules
[Info  - 14:47:00] Auto-excluding **/__pycache__
[Info  - 14:47:00] Auto-excluding **/.*
[Warn  - 14:47:00] stubPath file:///home/danny/src/odoo-18.0/typings is not a valid directory.
[Info  - 14:47:01] Assuming Python version 3.12.7.final.0
[Info  - 14:47:05] Found 16272 source files
[Info  - 15:24:59] Starting service instance "<default>"
Received pythonPath from Python extension: /bin/python3.12
[Info  - 15:25:00] Setting pythonPath for service "<default>": "/bin/python3.12"
[Info  - 15:25:00] No include entries specified; assuming /<default workspace root>
[Info  - 15:25:00] Auto-excluding **/node_modules
[Info  - 15:25:00] Auto-excluding **/__pycache__
[Info  - 15:25:00] Auto-excluding **/.*
[Info  - 15:25:00] Assuming Python version 3.12.7.final.0
[Error - 15:25:00] File or directory "/<default workspace root>" does not exist.
[Info  - 15:25:00] No source files found.
[Info  - 15:25:00] Background analysis(3) root directory: file:///home/danny/.cursor/extensions/trinhanhngoc.vscode-odoo-0.38.4-linux-x64/dist
[Info  - 15:25:00] Background analysis(3) started
[Info  - 15:25:03] [BG(2)] Long operation: checking: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2017ms)
[Info  - 15:25:03] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2083ms)
[Info  - 15:29:00] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2023ms)
[Info  - 15:33:19] [BG(2)] Long operation: checking: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2056ms)
[Info  - 15:33:19] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2102ms)
[Info  - 15:42:29] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2045ms)
[Info  - 15:55:03] [BG(2)] Long operation: checking: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2204ms)
[Info  - 15:55:03] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2250ms)
[Info  - 16:04:57] [BG(2)] Long operation: checking: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2156ms)
[Info  - 16:04:57] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2209ms)
[Info  - 16:23:21] [BG(2)] Long operation: checking: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2276ms)
[Info  - 16:23:21] [BG(2)] Long operation: analyzing: file:///home/danny/src/odoo-18.0/odoo/src/odoo/odoo/fields.py (2327ms)
```

**Comment by trinhanhngoc** [comment]
@dannyadair ,

Yes, Odoo IDE is built on the top of Pyright. You can create issues for Odoo: https://github.com/odoo/odoo/issues

**Comment by dannyadair** [comment]
Ok thank you. I'll close this issue now.

I was just wondering about the warning because the import is not a real error, and ContextType etc. are defined in odoo.api just fine (though not listed in __all__). I'll just ignore that

**Comment by trinhanhngoc** [comment]
@dannyadair ,

Sorry, that's my wrong. The import errors caused by missing module members in https://github.com/odoo-ide/odoo-stubs. I will update odoo-stubs to fix it. Thanks for the report.

**Comment by dannyadair** [comment]
Thank you!
